# -*- coding: utf-8 -*-
"""Challenge_TelecomX_2_BR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-xxqT_xG0QJyqIebTQcJdSPayh37Nu3j

<center>
<b><font size="10">Telecom X - Parte 2</font></b>
</center>

<br/>
<center>
<b><font color="blue" size="6">Prevendo Cancelamento</font></b>
</center>

🎯 <b><font color="blue">MISSÃO:</font></b>

 - Desenvolver **modelos preditivos** capazes de prever quais clientes têm maior chance de cancelar seus serviços.

 - A empresa quer **antecipar o problema da evasão**, assim será construído um pipeline robusto para essa etapa inicial de modelagem.

🧠 <b><font color="blue">OBJETIVO DO DESAFIO:</font></b>

 - Preparar os dados para a **modelagem** (*tratamento, encoding, normalização*).

 - Realizar **análise de correlação** e seleção de variáveis.

 - Treinar dois ou mais modelos de classificação.

 - Avaliar o desempenho dos modelos com **métricas**.

 - **Interpretar os resultados**, incluindo a importância das variáveis.

 - Criar uma **conclusão estratégica** apontando os principais fatores que influenciam a evasão.

#📌 <b><font color="blue" size="6">EXTRAÇÃO</font></b>


---

Para iniciar análise, importado os [dados da API da Telecom X](https://drive.google.com/file/d/1Dul9YDaHCzXo8jFJKceEhzarRkjwLYnK/view?usp=drive_link). Esses dados estão disponíveis no formato `CSV` e contêm as informações já tratadas.
"""

import pandas as pd
import requests
import json
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import gdown
from IPython.display import display, HTML

# ✅ ID do arquivo no Google Drive
file_id = '1Dul9YDaHCzXo8jFJKceEhzarRkjwLYnK'
url = f'https://drive.google.com/uc?id={file_id}'

# ⬇️ Baixar o arquivo
gdown.download(url, 'dados_tratados.csv', quiet=False)

# 📖 Ler os dados
dados = pd.read_csv('dados_tratados.csv')
dados.head()

"""#🔧 <b><font color="blue" size="6">PREPARAÇÃO DOS DADOS</font></b>


---

## 🎯<b><font color="blue">Remoção de Colunas Irrelevantes</font></b>

Removido coluna com IDs, estimativas e valores duplicados em outras colunas. Essas colunas não ajudam na previsão da evasão e podem até prejudicar o desempenho dos modelos.
"""

# Calcular correlação apenas entre colunas numéricas
dados_numericos = dados.select_dtypes(include=['number', 'bool'])
correlacao = dados_numericos.corr().abs()

# Pegar pares com alta correlação
pares_correlacionados = [
    (col1, col2)
    for col1 in correlacao.columns
    for col2 in correlacao.columns
    if col1 != col2 and correlacao.loc[col1, col2] > 0.95
]

print("🔁 PARES DE COLUNAS COM ALTA CORRELAÇÃO:")
print('-'*41)
for col1, col2 in pares_correlacionados:
    print(f"{col1}  🔛  {col2}")

# Remover as colunas com alta correlação
dados = dados.drop(['ID_Cliente', 'tempo_estimado_meses', 'Conta_Diarias', 'Valor_Total'], axis=1)

# Remover registros onde o valor é 'Não informado'
dados = dados[dados['Cancelamento'] != 'Não informado']


dados.head()

"""## 🎯 <b><font color="blue">Encoding</font></b>

Inicialmente foi identificado os valores únicos de cada coluna e posteriormente transformado as variáveis categóricas em formato numérico para torná-las compatíveis com algoritmos de machine learning. Utilizou-se um método de codificação adequado, como o **one-hot encoding**.
"""

# Para saber os valores únicos por coluna e quantidade.
for col in dados.select_dtypes(include='object').columns:
    titulo = f"<strong style='font-size: 15px;'>➡️  {col.upper()}</strong>"
    display(HTML(titulo))
    display(dados[col].value_counts(dropna=False).head(3).to_frame(name='Frequência'))
    print("-" * 35)

# Passo 1: Mapear os valores para binário
import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    dados = dados.replace({'Yes': 1, 'No': 0})
    dados = dados.replace({'Female': 1, 'Male': 0})
    dados = dados.replace({'True': 1, 'False': 0})

dados.info()

# Passo 2: Identificar colunas que têm só 0 e 1
binarias = [col for col in dados.columns if set(dados[col].dropna().unique()).issubset({0, 1})]

# Passo 3: Converter essas colunas para booleano
dados[binarias] = dados[binarias].astype(bool)

dados.info()

# Passo 4: One-hot encoding para todas as colunas categóricas multiclasse
dados = pd.get_dummies(dados, drop_first=True)

dados.info()

# Passo 5: Calcular novamente a correlação apenas entre colunas numéricas
dados_numericos = dados.select_dtypes(include=['number', 'bool'])
correlacao = dados_numericos.corr().abs()

# Pegar pares com alta correlação
pares_correlacionados = [
    (col1, col2)
    for col1 in correlacao.columns
    for col2 in correlacao.columns
    if col1 != col2 and correlacao.loc[col1, col2] > 0.95
]

print("🔁 PARES DE COLUNAS COM ALTA CORRELAÇÃO:")
print('-'*40)
for col1, col2 in pares_correlacionados:
    print(f"{col1}  🔛  {col2}")

# Passo 6: Remover colunas com alta correlação:
dados = dados.drop([ 'Multiplas_Linhas_No phone service',
    'Backup_Online_No internet service',
    'Protecao_Dispositivo_No internet service',
    'Suporte_Tecnico_No internet service',
    'Streaming_TV_No internet service',
    'Streaming_Filmes_No internet service'], axis=1)

# Remover registros onde o valor é 'Não informado'
dados = dados[dados['Cancelamento'] != 'Não informado']


dados.head()

"""## 🎯 <b><font color="blue">Verificação da Proporção de Evasão</font></b>

Calculamos a proporção de clientes cancelados (evadidos) e os que permaneceram. A distribuição será usada para definir se o dataset está balanceado.
"""

# Frequência absoluta e relativa da coluna Cancelamento
frequencia = dados['Cancelamento'].value_counts()
proporcao = dados['Cancelamento'].value_counts(normalize=True) * 100

# Visualizar com gráfico de barras
plt.figure(figsize=(10, 6))
sns.barplot(x=proporcao.index, y=proporcao.values, hue=proporcao.index, palette='coolwarm', legend=False)
plt.ylabel('Proporção (%)')
plt.title('Distribuição da Evasão de Clientes')
plt.show()

# Exibir os resultados
print("\n📊 FREQUENCIA ABSOLUTA:")
print("-" * 23)
print(frequencia)
print("-\n" * 1)
print("📈 PROPORÇÃO (%):")
print("-" * 17)
print(proporcao)
print("-\n")

"""###📌 Após rodar seu código, veja:


 - **Equilíbrio**: Quando as classes estão próximas de 50% / 50%.

 - **Gerenciável quando próximo de 70% / 30%** .Se 70% dos clientes permaneceram e 30% cancelaram, ainda é possível treinar bons modelos com técnicas de balanceamento

 - **Desequilíbrio forte**: Quando uma classe tem 80% ou mais dos registros (ex: 80% "Não" e 20% "Sim"), o modelo pode ignorar a classe minoritária, e será importante:

  - Aplicar técnicas de balanceamento (como oversampling com SMOTE, undersampling, etc.);

  - Escolher métricas apropriadas (como f1-score, recall, AUC) — e não apenas acurácia.

## 🎯 <b><font color="blue">Balanceamento de Classes</font></b>

Para aprofundar a análise, foi aplicado técnicas de balanceamento como **undersampling** , **oversampling** e **SMOTE**. Em situações de forte desbalanceamento, ferramentas como o **SMOTE** podem ser úteis para gerar exemplos sintéticos da classe minoritária.
"""

# Separar features(X) e target(y)
X = dados.drop('Cancelamento', axis=1)
y = dados['Cancelamento']

# Oversampling com RandomOverSampler (Duplica registros da classe minoritária)

from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
X_res, y_res = ros.fit_resample(X, y)

print("DISTRIBUIÇÃO APÓS OVERSAMPLING:")
print("-" * 31)
print(pd.Series(y_res).value_counts())

# Undersampling com RandomUnderSampler (Remove registros da classe majoritária)
# Gera novas amostras sintéticas da classe minoritária, em vez de apenas copiar.

from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=42)
X_res, y_res = rus.fit_resample(X, y)

print("DISTRIBUIÇÃO APÓS UNDERSAMPLING:")
print("-" * 32)
print(pd.Series(y_res).value_counts())

# SMOTE (Synthetic Minority Over-sampling Technique)
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

print("DISTRIBUIÇÃO APÓS SMOTE:")
print("-" * 24)
print(pd.Series(y_res).value_counts())

"""### 🧪 **Balanceamento de Classes**

Antes da criação dos modelos, foi analisada a proporção entre as classes da variável-alvo `Cancelamento`, que indica se o cliente **evadiu** (1) ou **permaneceu** (0). Identificou-se um desequilíbrio entre as classes, o que poderia comprometer o desempenho preditivo dos algoritmos, especialmente em relação à detecção de clientes propensos à evasão.

Para lidar com esse problema, foram testadas três técnicas de balanceamento:

- **Oversampling com `RandomOverSampler`**: Aumenta a quantidade da classe minoritária replicando seus exemplos.
- **Undersampling com `RandomUnderSampler`**: Reduz a quantidade da classe majoritária removendo exemplos.
- **`SMOTE` (Synthetic Minority Over-sampling Technique)**: Gera exemplos sintéticos da classe minoritária com base nos vizinhos mais próximos.

Após a comparação das distribuições, optou-se por seguir com a técnica **SMOTE**, pois ela mantém todos os dados originais e cria novos registros de forma artificial, evitando duplicações e reduzindo o risco de overfitting.

Os dados balanceados foram então utilizados para treinar e avaliar os modelos preditivos. O desempenho foi posteriormente analisado por meio de métricas como **precisão**, **recall**, **f1-score** e **matriz de confusão**, que serão apresentados nas próximas etapas.

## 🎯  <b><font color="blue">Normalização ou Padronização </font></b>

Foi avaliado a necessidade de normalizar ou padronizar os dados, conforme os modelos que serão aplicados.
Modelos baseados em distância, como KNN, SVM, Regressão Logística e Redes Neurais, requerem esse pré-processamento.
Já modelos baseados em árvore, como Decision Tree, Random Forest e XGBoost, não são sensíveis à escala dos dados.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Separar X e y
X = dados.drop(columns=['Cancelamento'])
y = dados['Cancelamento']

# Dividir treino e teste (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Identificar colunas numéricas para padronizar
colunas_numericas = ['Meses_de_Contrato', 'Valor_Mensal']

# Criar cópias para não modificar original
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

# Aplicar StandardScaler só nas colunas numéricas
scaler = StandardScaler()
X_train_scaled[colunas_numericas] = scaler.fit_transform(X_train[colunas_numericas])
X_test_scaled[colunas_numericas] = scaler.transform(X_test[colunas_numericas])

# Agora se pode usar X_train_scaled e X_test_scaled para treinar modelos sensíveis à escala.

"""### ⚙️ **Normalização / Padronização dos Dados**

Como parte do pré-processamento, foi aplicada a **padronização** dos atributos numéricos, utilizando a técnica `StandardScaler`, que transforma os dados para que tenham média zero e desvio padrão um.

Esse passo é fundamental para o bom desempenho de algoritmos que são sensíveis à escala dos dados, como:

- **KNN** (K-Nearest Neighbors)
- **SVM** (Support Vector Machines)
- **Regressão Logística**
- **Redes Neurais**

A padronização foi aplicada **apenas após o balanceamento das classes e a separação entre dados de treino e teste**, para evitar vazamento de dados e garantir que as transformações ocorram apenas com base nos dados de treino. Com isso, garantimos uma comparação justa e válida durante a avaliação dos modelos.

# 📊 <b><font color="blue" size="6">CORRELAÇÃO E SELEÇÃO DE VARIÁVEIS</font></b>

## 🎯 <b><font color="green">Análise de Correlação</font></b>

A matriz de correlação é útil para identificar relações entre variáveis numéricas. Observe especialmente quais variáveis apresentam maior correlação com a evasão, pois elas podem ser fortes candidatas para o modelo preditivo.
"""

# Identificar as colunas numéricas automaticamente
colunas_numericas = dados.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Para garantir que a coluna alvo 'Cancelamento' esteja incluída
if 'Cancelamento' not in colunas_numericas:
    colunas_numericas.append('Cancelamento')

# Criar um DataFrame apenas com as colunas numéricas
dados_numericos = dados[colunas_numericas]


# Calcular matriz de correlação
corr = dados_numericos.corr()

# Visualizar matriz de correlação
plt.figure(figsize=(10, 8))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", square=True)
plt.title('Matriz de Correlação das Variáveis Numéricas')
plt.show()


# Analisar correlação com evasão ---
corr_com_alvo = corr['Cancelamento'].drop('Cancelamento').sort_values(ascending=False)

"""### 🔍 **Análise de Correlação**

Foi utilizada a matriz de correlação para identificar possíveis relações entre as variáveis numéricas e a variável-alvo `Cancelamento`. A análise permite identificar variáveis que apresentam maior influência na evasão dos clientes.

A matriz de correlação retornou as variáveis `Meses_de_Contrato` e `Valor_Mensal`, pois são as únicas variáveis numéricas contínuas do conjunto de dados. As demais variáveis são majoritariamente binárias (indicadoras), o que limita sua visualização na matriz padrão.

Para complementar, foi plotado um gráfico com as variáveis mais correlacionadas com `Cancelamento`, com o objetivo de enriquecer a análise e identificar fatores relevantes para a evasão:

 - A **correlação entre “Meses_de_Contrato” e “Valor_Mensal”  é fraca (0.25)**.

 - A **correlação entre “Meses_de_Contrato” e “Cancelamento”  é fraca (0.35)**.

 - A **correlação entre “Valor_Mensal” e “Cancelamento”  é fraca (0.19)**.

🔎 *Isso sugere que não há uma relação linear forte entre o tempo de contrato e o valor pago mensalmente, e entre cada uma das variáveis com o cancelamento.*

## 🎯 <b><font color="green">Análise Direcionadas</font></b>

Nesta etapa, analisamos como duas variáveis principais — **Meses de Contrato** e **Valor Mensal** — se comportam em relação ao **Cancelamento (Evasão)** dos clientes.
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 6))  # 1 linha, 2 colunas

# Boxplot com hue e legend=False para evitar warning
sns.boxplot(ax=axes[0], x='Cancelamento', y='Meses_de_Contrato', hue='Cancelamento', palette='coolwarm', data=dados, legend=False)
axes[0].set_title('Tempo de Contrato por Evasão',fontsize=12)
axes[0].set_ylabel('Meses de Contrato')

sns.stripplot(ax=axes[1], x='Cancelamento', y='Valor_Mensal', hue='Cancelamento',jitter=True, alpha=0.5, data=dados, legend=False)
axes[1].set_title('Valor Mensal por Evasão', fontsize=12)
axes[1].set_ylabel('Valor Mensal')

plt.tight_layout()

# Aumenta o espaço horizontal entre os gráficos
plt.subplots_adjust(hspace=0.5, wspace=0.3)
plt.show()

"""### 🎯 **Análise Direcionada**



---

#### 📊 **Gráfico 1**: *Boxplot - Tempo de Contrato por Evasão*

O **boxplot** apresenta a distribuição dos **meses de contrato** para clientes que **permaneceram (0)** e os que **evadiram (1)**.

- A mediana (linha central da caixa) mostra a tendência central de cada grupo.
- As caixas representam o intervalo interquartil (50% central dos dados).
- Pontos fora da caixa (outliers) indicam clientes com tempos de contrato muito diferentes da maioria.

⇣⇣⇣

**🧐 Interpretação:**  
Podemos observar que clientes que evadiram tendem a ter um **tempo de contrato menor** do que os que permaneceram. Isso pode indicar que a evasão ocorre mais frequentemente nos primeiros meses de contrato.

---

#### 🎯 **Gráfico 2**: *Stripplot - Valor Mensal por Evasão*

O **stripplot** (também chamado de *scatter plot categórico*) mostra **cada cliente individualmente**, posicionando seus **valores mensais** em relação à evasão.

- Cada ponto representa um cliente.
- Os pontos estão "espalhados" horizontalmente (via `jitter`) para facilitar a visualização da densidade.

⇣⇣⇣

**🧐 Interpretação:**

Apesar de haver sobreposição, é possível notar uma **concentração maior de valores mensais mais altos entre os clientes que evadiram (1)**, sugerindo que **valores mais elevados podem estar relacionados à evasão**.

---

Esses dois gráficos ajudam a entender melhor **quais fatores estão associados à decisão dos clientes em cancelar os serviços.**

# 🤖 <b><font color="blue" size="6">MODELAGEM PREDITIVA</font></b>

## 🎯 <b><font color="blue">Separação de Dados</font></b>

Uma divisão comum é 70% para treino e 30% para teste, ou 80/20, dependendo do tamanho da base de dados.
"""

# Dividir treino e teste (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

"""## 🎯 <b><font color="blue">Criação de Modelos</font></b>

Foi criado 4 modelos diferentes para prever a evasão de clientes:

 - *Regressão Logística* e *KNN* que exige normalização.

 - *Árvore de Decisão* e *Random Forest* que não exige normalização.

"""

# MODELO 1: Regressão Logística (com normalização)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Normalização apenas para o Modelo 1
scaler = StandardScaler()
X_train_norm = scaler.fit_transform(X_train)
X_test_norm = scaler.transform(X_test)

# Treinar modelo com dados normalizados
modelo_log = LogisticRegression()
modelo_log.fit(X_train_norm, y_train)

# Previsões
y_pred_log = modelo_log.predict(X_test_norm)

# Avaliação
print("🔍 REGRESSÃO LOGÍSTICA")
print("-" * 23)
print(confusion_matrix(y_test, y_pred_log))
print(classification_report(y_test, y_pred_log))

# MODELO 2: Random Forest

from sklearn.ensemble import RandomForestClassifier

# Treinar modelo com dados originais
modelo_rf = RandomForestClassifier(random_state=42)
modelo_rf.fit(X_train, y_train)

# Previsões
y_pred_rf = modelo_rf.predict(X_test)

# Avaliação
print("🌳 RANDOM FOREST")
print("-" * 17)
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

# MODELO 3: KNN - K Vizinhos Mais Próximos (com normalização)
from sklearn.neighbors import KNeighborsClassifier

modelo_knn = KNeighborsClassifier(n_neighbors=5)
modelo_knn.fit(X_train_norm, y_train)
y_pred_knn = modelo_knn.predict(X_test_norm)

# Avaliação
print("🔍 KNN")
print("-" * 10)
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

# MODELO 4: Árvore de Decisão (sem normalização)
from sklearn.tree import DecisionTreeClassifier

modelo_dt = DecisionTreeClassifier(random_state=42)
modelo_dt.fit(X_train, y_train)
y_pred_dt = modelo_dt.predict(X_test)

# Avaliação
print("🌳 ÁRVORE DE DECISÃO")
print("-" * 21)
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Função para gerar métricas + matriz de confusão como string
def gerar_metricas(nome, modelo, X_test, y_test, y_pred):
    cm = confusion_matrix(y_test, y_pred)
    cm_str = f"[[{cm[0][0]}, {cm[0][1]}], [{cm[1][0]}, {cm[1][1]}]]"

    return {
        'Modelo': nome,
        'Acurácia': accuracy_score(y_test, y_pred),
        'Precisão': precision_score(y_test, y_pred),
        'Recall': recall_score(y_test, y_pred),
        'F1-Score': f1_score(y_test, y_pred),
        'Matriz de Confusão': cm_str
    }

# Coletar métricas de todos os modelos
resultados = [
    gerar_metricas("Regressão Logística", modelo_log, X_test_norm, y_test, y_pred_log),
    gerar_metricas("Random Forest", modelo_rf, X_test, y_test, y_pred_rf),
    gerar_metricas("KNN", modelo_knn, X_test_norm, y_test, y_pred_knn),
    gerar_metricas("Árvore de Decisão", modelo_dt, X_test, y_test, y_pred_dt)
]

# Criar DataFrame
df_resultados = pd.DataFrame(resultados)
df_resultados = df_resultados.sort_values(by='F1-Score', ascending=False)

# Exibir a tabela
print("📊 COMPARATIVO DE MODELOS")
print("-" * 26)
display(df_resultados.round(4))

# Criar DataFrame com os dados fornecidos
dados_modelos = pd.DataFrame({
    'Modelo': ['Regressão Logística', 'Random Forest', 'KNN', 'Árvore de Decisão'],
    'Acurácia': [0.7996, 0.7896, 0.7569, 0.7264],
    'Precisão': [0.6544, 0.6434, 0.5473, 0.4859],
    'Recall': [0.5214, 0.4679, 0.4947, 0.5053],
    'F1-Score': [0.5804, 0.5418, 0.5197, 0.4954]
})

# Plotar gráfico de barras para cada métrica
dados_modelos.set_index('Modelo').plot(kind='bar', figsize=(12, 6), colormap='Set3')
plt.title('Comparativo de Desempenho dos Modelos')
plt.ylabel('Pontuação')
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.grid(axis='y')
plt.legend(title='Métricas')
plt.tight_layout()
plt.show()

"""## 🤖  <b><font color="blue">Avaliação dos Modelos </font></b>

Para prever a evasão de clientes, foram utilizados **quatro modelos diferentes**, com e sem normalização. Cada modelo foi avaliado utilizando as seguintes métricas:

- **Acurácia**  
- **Precisão**  
- **Recall**  
- **F1-score**  
- **Matriz de confusão**

<br/>

### 📌 **MODELO 1**: *Regressão Logística* (com normalização)

- Modelo linear, indicado para **classificação binária**.  
- Requer **normalização dos dados**, pois é sensível à escala das variáveis.  
- Fácil de interpretar e útil para identificar variáveis relevantes.  
- Serviu como **modelo base** e apresentou **o melhor desempenho geral** nas métricas.

---

### 📌 **MODELO 2**: *Random Forest* (sem normalização)

- Modelo não linear baseado em múltiplas árvores de decisão.  
- **Não precisa de normalização**, pois suas decisões são baseadas em cortes.  
- Robusto contra overfitting e apto a capturar relações complexas entre variáveis.  
- Teve desempenho sólido, porém com menor recall em comparação à regressão logística.

---

### 📌 **MODELO 3**: *KNN* – K Vizinhos Mais Próximos (com normalização)

- Classifica os clientes com base na **distância dos vizinhos mais próximos**.  
- Requer **normalização**, pois é altamente sensível à escala das variáveis.  
- Simples e intuitivo, mas pode ter **performance inferior com dados desbalanceados**.  
- Apresentou **métricas medianas** e sinal de **underfitting**.

---

### 📌 **MODELO 4**: *Árvore de Decisão* (sem normalização)

- Modelo interpretável baseado em regras do tipo "if-else".  
- **Não exige normalização**.  
- Pode se ajustar bem aos dados, mas é suscetível ao **overfitting** se não regulado.  
- Foi o modelo com **menor desempenho geral**, indicando **underfitting**.

<br/>

### 🏆 <b><font color="blue">**CONCLUSÃO** </font></b>: Melhor Modelo é **Regressão Logística**

Após aplicar e comparar os quatro modelos (Regressão Logística, Random Forest, KNN e Árvore de Decisão), considerando as métricas de desempenho (Acurácia, Precisão, Recall, F1-Score e Matriz de Confusão), conclui-se:

- 🔹 **Regressão Logística** apresentou o melhor desempenho geral:
  - Maior **acurácia (0.7996)** e **F1-Score (0.5804)**.
  - Bom equilíbrio entre **precisão (0.6544)** e **recall (0.5214)**.
  - Modelo simples, interpretável e eficiente, ideal para começar.

- 🔹 **Random Forest** teve desempenho próximo, porém com recall mais baixo, o que pode impactar a detecção de clientes que realmente evadiriam.

- 🔹 **KNN** e **Árvore de Decisão** apresentaram **desempenho inferior**, com menor F1-Score e sinais de **underfitting** (pouca capacidade de generalização).

<br/>

A <b><font color="blue">**Regressão Logística** </font></b> é o modelo mais indicado neste cenário, combinando boa performance, fácil aplicação e excelente interpretabilidade para ações estratégicas nas empresas.

#🚀 <b><font color="blue" size="6">INTERPRETAÇÃO & CONCLUSÃO</font></b>

## 🔍 <b><font color="green">Análise de Importância das Variáveis </font></b>

O gráfico abaixo exibe as variáveis mais relevantes identificadas pelo modelo **Regressão Logística**, treinado com dados normalizados, para prever a **evasão de clientes**.

As variáveis posicionadas no topo do gráfico apresentam **maior influência nas decisões do modelo**, com base na magnitude dos coeficientes. Isso significa que pequenas variações nessas variáveis têm um impacto significativo na probabilidade de um cliente cancelar os serviços.
"""

# Extrair coeficientes do modelo treinado
coeficientes = modelo_log.coef_[0]

# Importância: valor absoluto dos coeficientes
importancias = np.abs(coeficientes)

# Criar DataFrame com variáveis e suas importâncias
df_importancias = pd.DataFrame({
    'Variável': X_train.columns,
    'Importância': importancias
}).sort_values(by='Importância', ascending=False)

# Plotar gráfico com cor única suave, sem legenda e sem warning
plt.figure(figsize=(10, 6))
sns.barplot(
    x='Importância',
    y='Variável',
    data=df_importancias,
    color='skyblue'
)
plt.title('Importância das Variáveis - Regressão Logística')
plt.xlabel('Importância (|coeficiente|)')
plt.ylabel('Variáveis')
plt.tight_layout()
plt.show()

"""# 🧠 <b><font color="blue">Conclusão Geral da Análise</font></b>

A análise preditiva de evasão de clientes realizada neste projeto possibilitou extrair insights valiosos sobre o comportamento dos usuários e os fatores que mais contribuem para o cancelamento dos serviços.

<br/>

#### ✅ <b><font color="blue">Principais Conclusões:</font></b>

- **O modelo Regressão Logística apresentou o melhor desempenho** entre os avaliados, alcançando acurácia de aproximadamente **79,96%**, além de melhores resultados nas métricas de **Precisão (65,44%)**, **Recall (52,14%)** e **F1-Score (58,04%)**, essenciais para identificar corretamente clientes propensos à evasão.
- O modelo Random Forest, apesar de ter boa acurácia (78,96%), apresentou desempenho inferior nas métricas de precisão e recall, mostrando-se menos eficaz para o problema específico.
- As variáveis com maior impacto na previsão incluem:
  - **Tempo de Contrato**: clientes com menor tempo tendem a evadir mais.
  - **Valor Mensal**: valores maiores influenciam negativamente a permanência.
  - **Serviços adicionais** como segurança online, backup e suporte técnico mostraram relevância na modelagem.

<br/>

#### 🎯 <b><font color="blue">Recomendações Estratégicas:</font></b>

- **Desenvolver ações de retenção específicas** para clientes com contratos mais curtos e maior valor mensal, grupos que apresentam maior risco de evasão.
- **Oferecer pacotes personalizados ou descontos progressivos** para aumentar o tempo de fidelização e reduzir a taxa de cancelamento.
- **Utilizar o modelo de Regressão Logística para monitoramento contínuo** e antecipação de clientes com maior probabilidade de evasão, possibilitando intervenções proativas.

<br/>

> 🚀 Este projeto demonstra como técnicas de Machine Learning auxilia na compreensão de fatores essenciais para que a empresa possa **antecipar comportamentos de cancelamento** e direcionar **ações estratégicas de retenção**, como ofertas personalizadas, melhoria no atendimento ou revisão de pacotes de serviços.



"""